
server:
  port: 8083

spring:
  config:
    import: configserver:http://localhost:9296
  application:
    name: PAYMENT-API
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update
      properties: