
server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: ORDER-API
          uri: lb://ORDER-API
          predicates:
            - Path= /order/**
          filters:
            name: CircuitBreaker
            args:
              name: ORDER-API
              fallbackuri: forward:/orderServiceFallBack
            name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 1
        - id: PAYMENT-API
          uri: lb://PAYMENT-API
          predicates:
            - Path= /payment/**
          filters:
            name: CircuitBreaker
            args:
              name: PAYMENT-API
              fallbackuri: forward:/paymentServiceFallBack
            name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 1
        - id: PRODUCT-API
          uri: lb://PRODUCT-API
          predicates:
            - Path= /product/**
          filters:
            name: CircuitBreaker
            args:
              name: PRODUCT-API
              fallbackuri: forward:/productServiceFallBack
            name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 1